source 'https://rubygems.org'

gem 'rake', "~> 10.4"

gem 'activerecord', '~> 4.2', '>= 4.2.4'

gem 'mysql2', '~> 0.3.18'

gem 'byebug', "~> 6.0"

gem 'nokogiri', '1.6.6.2'

gem 'htmlentities', "~> 4.3"

gem "minitest", "~> 5.8"

gem 'factory_girl', '~> 4.5'
gem 'database_cleaner', '~> 1.5.1'